// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgQPaRQv6_rjUIMIChm-3pC0EACEmf5yA',
    appId: '1:698067853903:web:336ac53e6fa70b80be803a',
    messagingSenderId: '698067853903',
    projectId: 'delta-t-f42e3',
    authDomain: 'delta-t-f42e3.firebaseapp.com',
    databaseURL: 'https://delta-t-f42e3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'delta-t-f42e3.firebasestorage.app',
    measurementId: 'G-S4GEJ8YGQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfTGcVfXKqvQoPSCin-4hGvJeXWPS6XZM',
    appId: '1:698067853903:android:c367d43f2acf6443be803a',
    messagingSenderId: '698067853903',
    projectId: 'delta-t-f42e3',
    databaseURL: 'https://delta-t-f42e3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'delta-t-f42e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-VWAVnvlBCRZIZv_CFH_rNEB6V_skl80',
    appId: '1:698067853903:ios:9a63ea2185f8a963be803a',
    messagingSenderId: '698067853903',
    projectId: 'delta-t-f42e3',
    databaseURL: 'https://delta-t-f42e3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'delta-t-f42e3.firebasestorage.app',
    androidClientId: '698067853903-bf2naoa3336i6a4cmv5qg0sgpbplo396.apps.googleusercontent.com',
    iosClientId: '698067853903-b1uv6rckanqjgihbrl488rb4s66gg2a7.apps.googleusercontent.com',
    iosBundleId: 'com.example.deltat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-VWAVnvlBCRZIZv_CFH_rNEB6V_skl80',
    appId: '1:698067853903:ios:9a63ea2185f8a963be803a',
    messagingSenderId: '698067853903',
    projectId: 'delta-t-f42e3',
    databaseURL: 'https://delta-t-f42e3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'delta-t-f42e3.firebasestorage.app',
    androidClientId: '698067853903-bf2naoa3336i6a4cmv5qg0sgpbplo396.apps.googleusercontent.com',
    iosClientId: '698067853903-b1uv6rckanqjgihbrl488rb4s66gg2a7.apps.googleusercontent.com',
    iosBundleId: 'com.example.deltat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgQPaRQv6_rjUIMIChm-3pC0EACEmf5yA',
    appId: '1:698067853903:web:637f683380110e5dbe803a',
    messagingSenderId: '698067853903',
    projectId: 'delta-t-f42e3',
    authDomain: 'delta-t-f42e3.firebaseapp.com',
    databaseURL: 'https://delta-t-f42e3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'delta-t-f42e3.firebasestorage.app',
    measurementId: 'G-QM5909YB4R',
  );
}
